kind: pipeline
type: docker
name: blog_vitepress

trigger:
  branch:
    - main

steps:

  # 构建
  - name: build
    image: node:16
    commands:
      - node -v
      - yarn -v
      - yarn config set registry https://registry.npm.taobao.org -g
      - yarn add --dev vitepress vue
      - yarn docs:build

  # 部署
  - name:  deploy
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_host
      username: root
      password: 
        from_secret: ssh_password
      port: 22
      command_timeout: 2m
      target: /home/nginx/html/blog_web                 # target 拷贝文件到指定目录
      source: docs/.vitepress/dist                      # source 原文件 打包后的那个目录 相对路径

  # 移动文件位置
  - name: handle
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username: root
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 2m
      script:
        - echo begin handle file
        - pwd
        - cd /home/nginx/html/blog_web/docs/.vitepress
        - pwd
        - \cp -rf dist/ /home/nginx/html/blog_web
        - cd ../../
        - rm -rf docs/
        - echo end