name: sync dist to server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      # 安装依赖
      - name: install
        run: yarn add --dev vitepress vue
      # 打包
      - name: build dist
        run: yarn docs:build
      # 同步文件
      - name: sync file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: ${{ secrets.SOURCE_PATH }}
          target: ${{ secrets.TARGET_PATH }}